baseURL = "/"
languageCode = "en-gb"
title = "Scottish 6 Days"
publishDir = "docs"

[permalinks]
   blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Results"
    pre = "file-text"
    url = "/results/"
    weight = 2
  [[menu.main]]
    name = "Daily News"
    pre = "info"
    url = "/dailynews/"
    weight = 3
  [[menu.main]]
    name = "Programme"
    pre = "info"
    url = "/programme/"
    weight = 4
